### ISSUE TITLE
I tag

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/firstpage#2]

**Comment by lucifero55** [comment]
ehmm

**Comment by FabioZTessitore** [comment]
dimmi

**Comment by lucifero55** [comment]
non so cosa fare

**Comment by FabioZTessitore** [comment]
devi dirmi se ti è chiaro il file che ti ho mandato

**Comment by lucifero55** [comment]
so che il tag <p> si usa per il testo, ma (name="firma") non so cosa faccia.

**Comment by FabioZTessitore** [comment]
prima di tutto quando scrivi dei tag qui non mettere i simboli di maggiore e minore sennò non vengono visualizzati (guarda il tuo post precedente).

Così come scritto nel codice, a volte i tag presentano degli attributi che ne specificano delle proprietà (funzionamento, significato, ecc ecc). In questo caso è stato assegnato un nome al paragrafo (anche se non sai a cosa serve per ora, l'importante è capire il concetto)
