### ISSUE TITLE
Nidificare i tag

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/firstpage#3]
## Nidificare i tag

I tag possono essere inclusi all'interno di altri tag
prestando attenzione a chiudere prima il tag interno e poi quello esterno.

Es. Il tag `em` serve a mettere in evidenza una porzione del testo
e puo' naturalmente essere utilizzato all'interno di un paragrafo.

```html
<p>Il linguaggio HTML <em>non</em> sembra difficile</p>
```

**Comment by lucifero55** [comment]
tutto chiaro, attendo esercitazioni da svolgere
